<?php
defined('_JEXEC') or die; 
/**
 *  ======== I M P O R T A N T ======= R E A D === M E == BEFORE == EDITING
 * 
 * == DO NOT EDIT THIS FILE DIRECTLY ==
 * == DO IT AS A JOOMLA OVERRIDE ==
 * HOW? SIMPLE: FIRST COPY THE CONTAINING "default" directory to 
 * /your/joomlapath/templates/<yourtemplatefolder>/html/mod_samlogin/default
 * then inside it you can edit this file as a standard joomla override
 * in this way you will upgrade-safe , you'll not lost your mods when 
 * a new samlogin version is released and you upgrade
 
 example:
 mkdir templates/<yourtemplatfolder>/html/mod_samlogin
 cp -r modules/mod_samlogin/tmpl/* templates/gantry/html/mod_samlogin/.
 then you can edit the latter
 
 * 
 */
?>
<div class="modSAMLogin">
	<span class="SAMLoginPre"><?php echo $params->get('preMessage',''); ?></span>
	 <?php if ($samloginParams->get('enable_samlogin', 1)) { ?>  
        <div class="SAMLogin" style='text-align:center;'>
			<form action="<?php echo $ssoLink; ?>" method="POST"> 
						<button type="submit" class="<?php echo $params->get('loginButtonClasses',"btn btn-primary uk-button uk-button-primary");?>">
							<i></i>
							<span> <?php echo $params->get('loginButtonLabel','SSO Login');?> </span>
						</button>
			</form>
	</div>
         <?php } ?>
        
         <?php if ($samloginParams->get('enable_fbconnect', 0)) { ?>
            	      <?php if ($samloginParams->get('enable_samlogin', 1)) { ?>   
            <div class="SamloginOrSpacer"><h4> <?php echo JText::_('SAMLOGIN_OR') ?> </h4></div>
                      <?php }?>
            <div class="samloginFacebookBlock">
                <a class="<?php echo $params->get('loginButtonClasses',"btn btn-primary uk-button uk-button-primary");?>"
                   href="<?php echo $facebookSSOLink; ?>">
		  <i></i>
		  <span> <?php echo $params->get('facebookloginButtonLabel',JText::_('SAMLOGIN_FACEBOOK_SSO'));?> </span>
		</a>
            </div>
          <?php }?>
            
	
</div>